### ISSUE TITLE
Remove custom processing plugin since up-to-date QGIS version is used?

### ISSUE THREAD

**Issue by j08lue** [TIGER-NET/WOIS_plugins#2]
@radosuav and @ctottrup, is it okay to remove our custom(izable) copy of the `processing` plugin for the WOIS 4.1 release? 

There are no modifications from the stock version, so we could save a bit of space and places where things can break.

**Comment by ctottrup** [comment]
tricky - difficult for me to judge, in any case and allthoug our current porcessing is a direct copy of the stock version then we will eventually move back to a customized version especially if we also want to look at the "issue" of hidding certain parameter settings behind an advanced tab.

**Comment by j08lue** [comment]
> eventually move back

That would not be a problem.

> "issue" of hidding certain parameter settings behind an advanced tab

But I forgot about this, sorry. Processing stays and I will look into hiding the parameters we talked about.

**Comment by ctottrup** [comment]
please remember no need to look at the parameters just yet ...

**Comment by radosuav** [comment]
Do you mean to remove it from WOIS 4.1 installation package? In that case I would prefer to keep it. Otherwise the issue could be that the users have an older version of Processing in C:\Users\user_name\.qgis2\python\plugins which would take precedence over over the new version which would be placed in C:\OSGeo4W64\apps\qgis\python\plugins\processing.

**Comment by j08lue** [comment]
> Do you mean to remove it from WOIS 4.1 installation package?

Yes, that is what I meant.

> Otherwise the issue could be that the users have an older version of Processing in C:\Users\user_name.qgis2\python\plugins which would take precedence over over the new version which would be placed in C:\OSGeo4W64\apps\qgis\python\plugins\processing.

The installer [does delete](https://github.com/TIGER-NET/WOIS_Installer/blob/fa6448e0ef1fe65c6503a8dcfc6e47ceb0e88dbb/woisInstaller.py#L150) the existing version, but good point.

Let us just keep it. I thought another issue I was facing (#3) was due to faulty processing toolbox, but it occurs even with the stock version. Closing this.
