### ISSUE TITLE
GRASS 6 missing from QGIS with Processing Toolbox v. 2.18?

### ISSUE THREAD

**Issue by j08lue** [TIGER-NET/WOIS_plugins#3]
When installing QGIS 2.18 from my pre-downloaded packages and with (custom or stock) Processing Toolbox 2.18, **GRASS 6 is missing completely**:

![image](https://cloud.githubusercontent.com/assets/3404817/22784458/6858f57e-eed0-11e6-9bb0-5fa8a356c808.png)

Not even re-installation with OSGeo4W Setup fixes this.

The weird thing is that GRASS 6 *did* work correctly when I installed from exactly the same packages (QGIS 2.18) but Processing Toolbox v. 2.14 from `ESA_Processing`.

@radosuav, do you have any clues on this? I am currently testing whether installing QGIS completely from online packages fixes the problem.

**Comment by radosuav** [comment]
Indeed something is not working right on my installation too. I'll have a look.

**Comment by j08lue** [comment]
Same upon online installation with OSGeo4W on a clean Windows 10 virtual machine.

**Comment by radosuav** [comment]
Have a look at https://github.com/DHI-GRAS/ESA_Processing/pull/15. The first commit is not in QGIS repo 2.18 branch, the second one is there since yesterday.

**Comment by j08lue** [comment]
I guess this is what we signed up for when chosing 2.18... Not that well-tested, it seems.

Thanks for sorting this out, @radosuav.

**Comment by j08lue** [comment]
Tested and works.
